### ISSUE TITLE
DOS2UNIX

### ISSUE THREAD

**Issue by MCTyler** [Forward-Action/google-compute-snapshot#1]
For Idiots like me that run in a Linux Environment can you please add the requirement of installing dos2unix and converting the file :). I spent 2 hours trying to figure this out! Thanks for the Script, It runs perfectly! Also if you create the cron job as root, I.E. >sudo crontab -e, then you do not need root in the command to run the script. (or am I doing something wrong?) This seems to run just fine from the command line `0 05 * * *  sh /1/snapshot.sh >> /var/log/cron/snapshot.log 2>&1`

**Comment by jacksegal** [comment]
Re dos2unix: My script is running on a Linux Debian box, so I'm shocked that you needed to use dos2unix.  Or are you talking about your local dev environment?  If you could let me know which Linux distro you're using that'd be great and also any error messages you got (before you ran dos2unix).  Just so that I can make the instructions as clear as possible...

Re cron: If you add it to root's cron job, then you don't need to add root to the command.  I do all my scripts in `/etc/cron.d`: https://help.ubuntu.com/community/CronHowto (Advanced Crontab section)

**Comment by MCTyler** [comment]
I'm using Ubuntu 16.04 Server. The error I got was in reference to command not found or something like that, Sorry I deleted those logs unless the exist somewhere else. The log it was writing to is the log you instructed we make in your tutorial. I still got the original file unconverted I'll run it real quick and give you the errors. First I get this with nano editor..., `File Name to Write [DOS Format]: snapshot.sh` then when I run  it...(Keep in mind, I ran this as non-sudo, so the permission error doesn't exist)....
`bugmansteve@instance-9:/var/www$ sh snapshot.sh
: not found: 3: snapshot.sh:
: not found: 7: snapshot.sh:
: not found: 10: snapshot.sh:
: not found: 13: snapshot.sh:
: not found: 16: snapshot.sh:
: not found: 19: snapshot.sh:
ERROR: (gcloud.compute.disks.snapshot) Some requests did not succeed:
 - Insufficient Permission


: not found: 22: snapshot.sh:
: not found: 23: snapshot.sh:
: not found: 24: snapshot.sh:
: not found: 28: snapshot.sh:
ERROR: (gcloud.compute.snapshots.list) Some requests did not succeed:
 - Insufficient Permission

: not found: 31: snapshot.sh:
snapshot.sh: 53: snapshot.sh: Syntax error: end of file unexpected (expecting "then")`

**Comment by MCTyler** [comment]
Here's the original file I copied and pasted into notepad++
[snapshot.zip](https://github.com/Forward-Action/google-compute-snapshot/files/247592/snapshot.zip)

**Comment by jacksegal** [comment]
Ah, you downloaded the file and pasted it into notepad++?  That would have been on a Windows machine then, which is where you would have got the DOS formatting issues.

It is better to pull the project on the server, or use a Linux friendly machine to edit the files.

**Comment by MCTyler** [comment]
Yea, I go back and forth between OS's depending on what I'm doing. Next time I copy a script I'll boot up my Linux Box and use GEdit! Still wouldn't hurt to clarify for dummies like me. :), I forked your script and did this, but you are mentioned on StackTrace for this particular Google search.

**Comment by jacksegal** [comment]
Yup - I've added it to the README - hopefully that makes it clear!  Thanks
